---
title: "p8105_hw2_tl3279"
author: "Tianqi Li"
date: "2024-09-30"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Problem 1
We loaded the dataset, selected the variables, and changed the entry variable from characters to logical. 1,868 rows × 20 columns.
```{r}
NYCsub = read_csv(
  "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) |>
  janitor::clean_names() |>
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, ada
    ) |>
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

```{r}
NYCsub |> 
  select(station_name, line) |> 
  distinct()
```
465 unique stations.

```{r}
NYCsub |> 
  filter(ada == TRUE) |> 
  select(station_name, line) |> 
  distinct()
```
84 are ASA compliant.

```{r}
NYCsub |> 
  filter(vending == "NO") |> 
  pull(entry) |> 
  mean()
```
37.7% of station entrances/exits without vending allow entrance.

```{r}
station_A = 
  NYCsub |> 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") |> 
  filter(route == "A") |> 
  select(station_name, line) |> 
  distinct()
station_A
```
60 distinct stations serve the A train

```{r}
station_A_ADA = 
  NYCsub |> 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") |> 
  filter(route == "A", ada == TRUE) |> 
  select(station_name, line) |> 
  distinct()
station_A_ADA
```
Of the stations that serve the A train 17 stations are ASA compliant.